//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvBuilder.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_messages
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string message { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual users users { get; set; }
    }
}
