//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvBuilder.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class arifkuru_cvEntities1 : DbContext
    {
        public arifkuru_cvEntities1()
            : base("name=arifkuru_cvEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<achievements> achievements { get; set; }
        public virtual DbSet<contact_messages> contact_messages { get; set; }
        public virtual DbSet<educations> educations { get; set; }
        public virtual DbSet<experiences> experiences { get; set; }
        public virtual DbSet<interests> interests { get; set; }
        public virtual DbSet<skills> skills { get; set; }
        public virtual DbSet<user_informations> user_informations { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<workflows> workflows { get; set; }
        public virtual DbSet<social_links> social_links { get; set; }
    }
}
