//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvBuilder.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile_visits
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public System.DateTime visited_at { get; set; }
        public string ip_address { get; set; }
        public string user_agent { get; set; }
        public string referrer { get; set; }
    
        public virtual users users { get; set; }
    }
}
