//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvBuilder.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class smtp_settings
    {
        public int id { get; set; }
        public string smtp_server { get; set; }
        public int smtp_port { get; set; }
        public string smtp_username { get; set; }
        public string smtp_password { get; set; }
        public string from_email { get; set; }
        public string from_name { get; set; }
        public bool enable_ssl { get; set; }
        public bool is_active { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
