//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvBuilder.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_informations
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string description { get; set; }
        public string profile_image { get; set; }
        public int user_id { get; set; }
        public string character_type { get; set; }
    
        public virtual users users { get; set; }
    }
}
